insert into Postal values(0555,'Scanning');
insert into Postal values(0800,'Høje Taastrup');
insert into Postal values(0877,'København C');
insert into Postal values(0892,'Sjælland USF P');
insert into Postal values(0893,'Sjælland USF B');
insert into Postal values(0894,'Udbetaling');
insert into Postal values(0897,'eBrevsprækken');
insert into Postal values(0899,'Kommuneservice');
insert into Postal values(0900,'København C');
insert into Postal values(0910,'København C');
insert into Postal values(0917,'Københavns Pakkecenter');
insert into Postal values(0918,'Københavns Pakke BRC');
insert into Postal values(0919,'Returprint BRC');
insert into Postal values(0929,'København C');
insert into Postal values(0960,'Internationalt Postcenter');
insert into Postal values(0999,'København C');
insert into Postal values(1000,'København K');
insert into Postal values(1001,'København K');
insert into Postal values(1002,'København K');
insert into Postal values(1003,'København K');
insert into Postal values(1004,'København K');
insert into Postal values(1005,'København K');
insert into Postal values(1006,'København K');
insert into Postal values(1007,'København K');
insert into Postal values(1008,'København K');
insert into Postal values(1009,'København K');
insert into Postal values(1010,'København K');
insert into Postal values(1011,'København K');
insert into Postal values(1012,'København K');
insert into Postal values(1013,'København K');
insert into Postal values(1014,'København K');
insert into Postal values(1015,'København K');
insert into Postal values(1016,'København K');
insert into Postal values(1017,'København K');
insert into Postal values(1018,'København K');
insert into Postal values(1019,'København K');
insert into Postal values(1020,'København K');
insert into Postal values(1021,'København K');
insert into Postal values(1022,'København K');
insert into Postal values(1023,'København K');
insert into Postal values(1024,'København K');
insert into Postal values(1025,'København K');
insert into Postal values(1026,'København K');
insert into Postal values(1045,'København K');
insert into Postal values(1050,'København K');
insert into Postal values(1051,'København K');
insert into Postal values(1052,'København K');
insert into Postal values(1053,'København K');
insert into Postal values(1054,'København K');
insert into Postal values(1055,'København K');
insert into Postal values(1055,'København K');
insert into Postal values(1056,'København K');
insert into Postal values(1057,'København K');
insert into Postal values(1058,'København K');
insert into Postal values(1059,'København K');
insert into Postal values(1060,'København K');
insert into Postal values(1061,'København K');
insert into Postal values(1062,'København K');
insert into Postal values(1063,'København K');
insert into Postal values(1064,'København K');
insert into Postal values(1065,'København K');
insert into Postal values(1066,'København K');
insert into Postal values(1067,'København K');
insert into Postal values(1068,'København K');
insert into Postal values(1069,'København K');
insert into Postal values(1070,'København K');
insert into Postal values(1071,'København K');
insert into Postal values(1072,'København K');
insert into Postal values(1073,'København K');
insert into Postal values(1074,'København K');
insert into Postal values(1092,'København K');
insert into Postal values(1093,'København K');
insert into Postal values(1095,'København K');
insert into Postal values(1098,'København K');
insert into Postal values(1100,'København K');
insert into Postal values(1101,'København K');
insert into Postal values(1102,'København K');
insert into Postal values(1103,'København K');
insert into Postal values(1104,'København K');
insert into Postal values(1105,'København K');
insert into Postal values(1106,'København K');
insert into Postal values(1107,'København K');
insert into Postal values(1110,'København K');
insert into Postal values(1111,'København K');
insert into Postal values(1112,'København K');
insert into Postal values(1113,'København K');
insert into Postal values(1114,'København K');
insert into Postal values(1115,'København K');
insert into Postal values(1116,'København K');
insert into Postal values(1117,'København K');
insert into Postal values(1118,'København K');
insert into Postal values(1119,'København K');
insert into Postal values(1120,'København K');
insert into Postal values(1121,'København K');
insert into Postal values(1122,'København K');
insert into Postal values(1123,'København K');
insert into Postal values(1124,'København K');
insert into Postal values(1125,'København K');
insert into Postal values(1126,'København K');
insert into Postal values(1127,'København K');
insert into Postal values(1128,'København K');
insert into Postal values(1129,'København K');
insert into Postal values(1130,'København K');
insert into Postal values(1131,'København K');
insert into Postal values(1140,'København K');
insert into Postal values(1147,'København K');
insert into Postal values(1148,'København K');
insert into Postal values(1150,'København K');
insert into Postal values(1151,'København K');
insert into Postal values(1152,'København K');
insert into Postal values(1153,'København K');
insert into Postal values(1154,'København K');
insert into Postal values(1155,'København K');
insert into Postal values(1156,'København K');
insert into Postal values(1157,'København K');
insert into Postal values(1158,'København K');
insert into Postal values(1159,'København K');
insert into Postal values(1160,'København K');
insert into Postal values(1161,'København K');
insert into Postal values(1162,'København K');
insert into Postal values(1163,'København K');
insert into Postal values(1164,'København K');
insert into Postal values(1165,'København K');
insert into Postal values(1165,'København K');
insert into Postal values(1166,'København K');
insert into Postal values(1167,'København K');
insert into Postal values(1168,'København K');
insert into Postal values(1169,'København K');
insert into Postal values(1170,'København K');
insert into Postal values(1171,'København K');
insert into Postal values(1172,'København K');
insert into Postal values(1173,'København K');
insert into Postal values(1174,'København K');
insert into Postal values(1175,'København K');
insert into Postal values(1200,'København K');
insert into Postal values(1201,'København K');
insert into Postal values(1202,'København K');
insert into Postal values(1203,'København K');
insert into Postal values(1204,'København K');
insert into Postal values(1205,'København K');
insert into Postal values(1206,'København K');
insert into Postal values(1207,'København K');
insert into Postal values(1208,'København K');
insert into Postal values(1209,'København K');
insert into Postal values(1210,'København K');
insert into Postal values(1211,'København K');
insert into Postal values(1212,'København K');
insert into Postal values(1213,'København K');
insert into Postal values(1214,'København K');
insert into Postal values(1215,'København K');
insert into Postal values(1216,'København K');
insert into Postal values(1217,'København K');
insert into Postal values(1218,'København K');
insert into Postal values(1218,'København K');
insert into Postal values(1218,'København K');
insert into Postal values(1218,'København K');
insert into Postal values(1218,'København K');
insert into Postal values(1218,'København K');
insert into Postal values(1219,'København K');
insert into Postal values(1220,'København K');
insert into Postal values(1221,'København K');
insert into Postal values(1240,'København K');
insert into Postal values(1250,'København K');
insert into Postal values(1251,'København K');
insert into Postal values(1252,'København K');
insert into Postal values(1253,'København K');
insert into Postal values(1254,'København K');
insert into Postal values(1255,'København K');
insert into Postal values(1256,'København K');
insert into Postal values(1257,'København K');
insert into Postal values(1258,'København K');
insert into Postal values(1259,'København K');
insert into Postal values(1259,'København K');
insert into Postal values(1260,'København K');
insert into Postal values(1261,'København K');
insert into Postal values(1263,'København K');
insert into Postal values(1263,'København K');
insert into Postal values(1264,'København K');
insert into Postal values(1265,'København K');
insert into Postal values(1266,'København K');
insert into Postal values(1267,'København K');
insert into Postal values(1268,'København K');
insert into Postal values(1270,'København K');
insert into Postal values(1271,'København K');
insert into Postal values(1291,'København K');
insert into Postal values(1300,'København K');
insert into Postal values(1301,'København K');
insert into Postal values(1302,'København K');
insert into Postal values(1303,'København K');
insert into Postal values(1304,'København K');
insert into Postal values(1306,'København K');
insert into Postal values(1307,'København K');
insert into Postal values(1307,'København K');
insert into Postal values(1308,'København K');
insert into Postal values(1309,'København K');
insert into Postal values(1310,'København K');
insert into Postal values(1311,'København K');
insert into Postal values(1312,'København K');
insert into Postal values(1313,'København K');
insert into Postal values(1314,'København K');
insert into Postal values(1315,'København K');
insert into Postal values(1316,'København K');
insert into Postal values(1317,'København K');
insert into Postal values(1318,'København K');
insert into Postal values(1319,'København K');
insert into Postal values(1320,'København K');
insert into Postal values(1321,'København K');
insert into Postal values(1322,'København K');
insert into Postal values(1323,'København K');
insert into Postal values(1324,'København K');
insert into Postal values(1325,'København K');
insert into Postal values(1326,'København K');
insert into Postal values(1327,'København K');
insert into Postal values(1328,'København K');
insert into Postal values(1329,'København K');
insert into Postal values(1349,'København K');
insert into Postal values(1350,'København K');
insert into Postal values(1352,'København K');
insert into Postal values(1353,'København K');
insert into Postal values(1354,'København K');
insert into Postal values(1355,'København K');
insert into Postal values(1356,'København K');
insert into Postal values(1357,'København K');
insert into Postal values(1358,'København K');
insert into Postal values(1359,'København K');
insert into Postal values(1359,'København K');
insert into Postal values(1360,'København K');
insert into Postal values(1361,'København K');
insert into Postal values(1361,'København K');
insert into Postal values(1362,'København K');
insert into Postal values(1363,'København K');
insert into Postal values(1364,'København K');
insert into Postal values(1365,'København K');
insert into Postal values(1366,'København K');
insert into Postal values(1367,'København K');
insert into Postal values(1368,'København K');
insert into Postal values(1369,'København K');
insert into Postal values(1370,'København K');
insert into Postal values(1371,'København K');
insert into Postal values(1400,'København K');
insert into Postal values(1400,'København K');
insert into Postal values(1401,'København K');
insert into Postal values(1402,'København K');
insert into Postal values(1402,'København K');
insert into Postal values(1402,'København K');
insert into Postal values(1402,'København K');
insert into Postal values(1402,'København K');
insert into Postal values(1403,'København K');
insert into Postal values(1404,'København K');
insert into Postal values(1406,'København K');
insert into Postal values(1407,'København K');
insert into Postal values(1408,'København K');
insert into Postal values(1409,'København K');
insert into Postal values(1410,'København K');
insert into Postal values(1411,'København K');
insert into Postal values(1411,'København K');
insert into Postal values(1412,'København K');
insert into Postal values(1413,'København K');
insert into Postal values(1414,'København K');
insert into Postal values(1415,'København K');
insert into Postal values(1416,'København K');
insert into Postal values(1417,'København K');
insert into Postal values(1418,'København K');
insert into Postal values(1419,'København K');
insert into Postal values(1420,'København K');
insert into Postal values(1421,'København K');
insert into Postal values(1422,'København K');
insert into Postal values(1423,'København K');
insert into Postal values(1424,'København K');
insert into Postal values(1425,'København K');
insert into Postal values(1426,'København K');
insert into Postal values(1427,'København K');
insert into Postal values(1428,'København K');
insert into Postal values(1429,'København K');
insert into Postal values(1430,'København K');
insert into Postal values(1431,'København K');
insert into Postal values(1432,'København K');
insert into Postal values(1432,'København K');
insert into Postal values(1432,'København K');
insert into Postal values(1433,'København K');
insert into Postal values(1433,'København K');
insert into Postal values(1433,'København K');
insert into Postal values(1433,'København K');
insert into Postal values(1433,'København K');
insert into Postal values(1433,'København K');
insert into Postal values(1433,'København K');
insert into Postal values(1434,'København K');
insert into Postal values(1435,'København K');
insert into Postal values(1436,'København K');
insert into Postal values(1436,'København K');
insert into Postal values(1436,'København K');
insert into Postal values(1436,'København K');
insert into Postal values(1436,'København K');
insert into Postal values(1436,'København K');
insert into Postal values(1436,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1437,'København K');
insert into Postal values(1438,'København K');
insert into Postal values(1438,'København K');
insert into Postal values(1438,'København K');
insert into Postal values(1438,'København K');
insert into Postal values(1438,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1439,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1440,'København K');
insert into Postal values(1441,'København K');
insert into Postal values(1441,'København K');
insert into Postal values(1441,'København K');
insert into Postal values(1448,'København K');
insert into Postal values(1450,'København K');
insert into Postal values(1451,'København K');
insert into Postal values(1452,'København K');
insert into Postal values(1453,'København K');
insert into Postal values(1454,'København K');
insert into Postal values(1455,'København K');
insert into Postal values(1456,'København K');
insert into Postal values(1457,'København K');
insert into Postal values(1458,'København K');
insert into Postal values(1459,'København K');
insert into Postal values(1460,'København K');
insert into Postal values(1461,'København K');
insert into Postal values(1462,'København K');
insert into Postal values(1463,'København K');
insert into Postal values(1464,'København K');
insert into Postal values(1465,'København K');
insert into Postal values(1466,'København K');
insert into Postal values(1467,'København K');
insert into Postal values(1468,'København K');
insert into Postal values(1470,'København K');
insert into Postal values(1471,'København K');
insert into Postal values(1472,'København K');
insert into Postal values(1473,'København K');
insert into Postal values(1500,'København V');
insert into Postal values(1501,'København V');
insert into Postal values(1502,'København V');
insert into Postal values(1503,'København V');
insert into Postal values(1504,'København V');
insert into Postal values(1505,'København V');
insert into Postal values(1506,'København V');
insert into Postal values(1507,'København V');
insert into Postal values(1508,'København V');
insert into Postal values(1509,'København V');
insert into Postal values(1510,'København V');
insert into Postal values(1512,'Returpost');
insert into Postal values(1513,'Centraltastning');
insert into Postal values(1532,'København V');
insert into Postal values(1533,'København V');
insert into Postal values(1550,'København V');
insert into Postal values(1550,'København V');
insert into Postal values(1551,'København V');
insert into Postal values(1552,'København V');
insert into Postal values(1553,'København V');
insert into Postal values(1553,'København V');
insert into Postal values(1554,'København V');
insert into Postal values(1555,'København V');
insert into Postal values(1556,'København V');
insert into Postal values(1557,'København V');
insert into Postal values(1558,'København V');
insert into Postal values(1559,'København V');
insert into Postal values(1560,'København V');
insert into Postal values(1561,'København V');
insert into Postal values(1561,'København V');
insert into Postal values(1562,'København V');
insert into Postal values(1563,'København V');
insert into Postal values(1564,'København V');
insert into Postal values(1566,'København V');
insert into Postal values(1567,'København V');
insert into Postal values(1568,'København V');
insert into Postal values(1569,'København V');
insert into Postal values(1570,'København V');
insert into Postal values(1570,'København V');
insert into Postal values(1571,'København V');
insert into Postal values(1572,'København V');
insert into Postal values(1573,'København V');
insert into Postal values(1574,'København V');
insert into Postal values(1575,'København V');
insert into Postal values(1576,'København V');
insert into Postal values(1577,'København V');
insert into Postal values(1577,'København V');
insert into Postal values(1577,'København V');
insert into Postal values(1592,'København V');
insert into Postal values(1599,'København V');
insert into Postal values(1600,'København V');
insert into Postal values(1601,'København V');
insert into Postal values(1602,'København V');
insert into Postal values(1603,'København V');
insert into Postal values(1604,'København V');
insert into Postal values(1605,'København V');
insert into Postal values(1606,'København V');
insert into Postal values(1607,'København V');
insert into Postal values(1608,'København V');
insert into Postal values(1609,'København V');
insert into Postal values(1610,'København V');
insert into Postal values(1611,'København V');
insert into Postal values(1612,'København V');
insert into Postal values(1613,'København V');
insert into Postal values(1614,'København V');
insert into Postal values(1615,'København V');
insert into Postal values(1616,'København V');
insert into Postal values(1617,'København V');
insert into Postal values(1618,'København V');
insert into Postal values(1619,'København V');
insert into Postal values(1620,'København V');
insert into Postal values(1620,'København V');
insert into Postal values(1621,'København V');
insert into Postal values(1622,'København V');
insert into Postal values(1623,'København V');
insert into Postal values(1624,'København V');
insert into Postal values(1630,'København V');
insert into Postal values(1631,'København V');
insert into Postal values(1632,'København V');
insert into Postal values(1633,'København V');
insert into Postal values(1634,'København V');
insert into Postal values(1635,'København V');
insert into Postal values(1640,'København V');
insert into Postal values(1650,'København V');
insert into Postal values(1651,'København V');
insert into Postal values(1652,'København V');
insert into Postal values(1653,'København V');
insert into Postal values(1654,'København V');
insert into Postal values(1655,'København V');
insert into Postal values(1656,'København V');
insert into Postal values(1657,'København V');
insert into Postal values(1658,'København V');
insert into Postal values(1659,'København V');
insert into Postal values(1660,'København V');
insert into Postal values(1660,'København V');
insert into Postal values(1661,'København V');
insert into Postal values(1662,'København V');
insert into Postal values(1663,'København V');
insert into Postal values(1664,'København V');
insert into Postal values(1665,'København V');
insert into Postal values(1666,'København V');
insert into Postal values(1667,'København V');
insert into Postal values(1668,'København V');
insert into Postal values(1669,'København V');
insert into Postal values(1670,'København V');
insert into Postal values(1671,'København V');
insert into Postal values(1671,'København V');
insert into Postal values(1672,'København V');
insert into Postal values(1673,'København V');
insert into Postal values(1674,'København V');
insert into Postal values(1675,'København V');
insert into Postal values(1676,'København V');
insert into Postal values(1677,'København V');
insert into Postal values(1699,'København V');
insert into Postal values(1700,'København V');
insert into Postal values(1701,'København V');
insert into Postal values(1702,'København V');
insert into Postal values(1703,'København V');
insert into Postal values(1704,'København V');
insert into Postal values(1705,'København V');
insert into Postal values(1706,'København V');
insert into Postal values(1707,'København V');
insert into Postal values(1708,'København V');
insert into Postal values(1709,'København V');
insert into Postal values(1710,'København V');
insert into Postal values(1711,'København V');
insert into Postal values(1711,'København V');
insert into Postal values(1712,'København V');
insert into Postal values(1713,'København V');
insert into Postal values(1714,'København V');
insert into Postal values(1715,'København V');
insert into Postal values(1716,'København V');
insert into Postal values(1717,'København V');
insert into Postal values(1718,'København V');
insert into Postal values(1719,'København V');
insert into Postal values(1720,'København V');
insert into Postal values(1721,'København V');
insert into Postal values(1722,'København V');
insert into Postal values(1723,'København V');
insert into Postal values(1724,'København V');
insert into Postal values(1725,'København V');
insert into Postal values(1726,'København V');
insert into Postal values(1727,'København V');
insert into Postal values(1728,'København V');
insert into Postal values(1729,'København V');
insert into Postal values(1730,'København V');
insert into Postal values(1731,'København V');
insert into Postal values(1732,'København V');
insert into Postal values(1733,'København V');
insert into Postal values(1734,'København V');
insert into Postal values(1735,'København V');
insert into Postal values(1736,'København V');
insert into Postal values(1737,'København V');
insert into Postal values(1738,'København V');
insert into Postal values(1739,'København V');
insert into Postal values(1749,'København V');
insert into Postal values(1750,'København V');
insert into Postal values(1751,'København V');
insert into Postal values(1752,'København V');
insert into Postal values(1753,'København V');
insert into Postal values(1754,'København V');
insert into Postal values(1755,'København V');
insert into Postal values(1756,'København V');
insert into Postal values(1757,'København V');
insert into Postal values(1758,'København V');
insert into Postal values(1759,'København V');
insert into Postal values(1760,'København V');
insert into Postal values(1761,'København V');
insert into Postal values(1762,'København V');
insert into Postal values(1763,'København V');
insert into Postal values(1764,'København V');
insert into Postal values(1765,'København V');
insert into Postal values(1766,'København V');
insert into Postal values(1770,'København V');
insert into Postal values(1771,'København V');
insert into Postal values(1772,'København V');
insert into Postal values(1773,'København V');
insert into Postal values(1774,'København V');
insert into Postal values(1775,'København V');
insert into Postal values(1777,'København V');
insert into Postal values(1780,'København V');
insert into Postal values(1782,'København V');
insert into Postal values(1785,'København V');
insert into Postal values(1786,'København V');
insert into Postal values(1787,'København V');
insert into Postal values(1790,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1799,'København V');
insert into Postal values(1800,'Frederiksberg C');
insert into Postal values(1801,'Frederiksberg C');
insert into Postal values(1802,'Frederiksberg C');
insert into Postal values(1803,'Frederiksberg C');
insert into Postal values(1804,'Frederiksberg C');
insert into Postal values(1805,'Frederiksberg C');
insert into Postal values(1806,'Frederiksberg C');
insert into Postal values(1807,'Frederiksberg C');
insert into Postal values(1808,'Frederiksberg C');
insert into Postal values(1809,'Frederiksberg C');
insert into Postal values(1810,'Frederiksberg C');
insert into Postal values(1811,'Frederiksberg C');
insert into Postal values(1812,'Frederiksberg C');
insert into Postal values(1813,'Frederiksberg C');
insert into Postal values(1814,'Frederiksberg C');
insert into Postal values(1815,'Frederiksberg C');
insert into Postal values(1816,'Frederiksberg C');
insert into Postal values(1817,'Frederiksberg C');
insert into Postal values(1818,'Frederiksberg C');
insert into Postal values(1819,'Frederiksberg C');
insert into Postal values(1820,'Frederiksberg C');
insert into Postal values(1822,'Frederiksberg C');
insert into Postal values(1823,'Frederiksberg C');
insert into Postal values(1824,'Frederiksberg C');
insert into Postal values(1825,'Frederiksberg C');
insert into Postal values(1826,'Frederiksberg C');
insert into Postal values(1827,'Frederiksberg C');
insert into Postal values(1828,'Frederiksberg C');
insert into Postal values(1829,'Frederiksberg C');
insert into Postal values(1835,'Frederiksberg C');
insert into Postal values(1850,'Frederiksberg C');
insert into Postal values(1851,'Frederiksberg C');
insert into Postal values(1852,'Frederiksberg C');
insert into Postal values(1853,'Frederiksberg C');
insert into Postal values(1854,'Frederiksberg C');
insert into Postal values(1855,'Frederiksberg C');
insert into Postal values(1856,'Frederiksberg C');
insert into Postal values(1857,'Frederiksberg C');
insert into Postal values(1860,'Frederiksberg C');
insert into Postal values(1861,'Frederiksberg C');
insert into Postal values(1862,'Frederiksberg C');
insert into Postal values(1863,'Frederiksberg C');
insert into Postal values(1864,'Frederiksberg C');
insert into Postal values(1865,'Frederiksberg C');
insert into Postal values(1866,'Frederiksberg C');
insert into Postal values(1867,'Frederiksberg C');
insert into Postal values(1868,'Frederiksberg C');
insert into Postal values(1870,'Frederiksberg C');
insert into Postal values(1871,'Frederiksberg C');
insert into Postal values(1872,'Frederiksberg C');
insert into Postal values(1873,'Frederiksberg C');
insert into Postal values(1874,'Frederiksberg C');
insert into Postal values(1875,'Frederiksberg C');
insert into Postal values(1876,'Frederiksberg C');
insert into Postal values(1877,'Frederiksberg C');
insert into Postal values(1878,'Frederiksberg C');
insert into Postal values(1879,'Frederiksberg C');
insert into Postal values(1900,'Frederiksberg C');
insert into Postal values(1901,'Frederiksberg C');
insert into Postal values(1902,'Frederiksberg C');
insert into Postal values(1903,'Frederiksberg C');
insert into Postal values(1904,'Frederiksberg C');
insert into Postal values(1905,'Frederiksberg C');
insert into Postal values(1906,'Frederiksberg C');
insert into Postal values(1908,'Frederiksberg C');
insert into Postal values(1909,'Frederiksberg C');
insert into Postal values(1910,'Frederiksberg C');
insert into Postal values(1911,'Frederiksberg C');
insert into Postal values(1912,'Frederiksberg C');
insert into Postal values(1913,'Frederiksberg C');
insert into Postal values(1914,'Frederiksberg C');
insert into Postal values(1915,'Frederiksberg C');
insert into Postal values(1916,'Frederiksberg C');
insert into Postal values(1917,'Frederiksberg C');
insert into Postal values(1920,'Frederiksberg C');
insert into Postal values(1921,'Frederiksberg C');
insert into Postal values(1922,'Frederiksberg C');
insert into Postal values(1923,'Frederiksberg C');
insert into Postal values(1924,'Frederiksberg C');
insert into Postal values(1925,'Frederiksberg C');
insert into Postal values(1926,'Frederiksberg C');
insert into Postal values(1927,'Frederiksberg C');
insert into Postal values(1928,'Frederiksberg C');
insert into Postal values(1931,'Frederiksberg C');
insert into Postal values(1950,'Frederiksberg C');
insert into Postal values(1951,'Frederiksberg C');
insert into Postal values(1952,'Frederiksberg C');
insert into Postal values(1953,'Frederiksberg C');
insert into Postal values(1954,'Frederiksberg C');
insert into Postal values(1955,'Frederiksberg C');
insert into Postal values(1956,'Frederiksberg C');
insert into Postal values(1957,'Frederiksberg C');
insert into Postal values(1958,'Frederiksberg C');
insert into Postal values(1959,'Frederiksberg C');
insert into Postal values(1960,'Frederiksberg C');
insert into Postal values(1961,'Frederiksberg C');
insert into Postal values(1962,'Frederiksberg C');
insert into Postal values(1963,'Frederiksberg C');
insert into Postal values(1964,'Frederiksberg C');
insert into Postal values(1965,'Frederiksberg C');
insert into Postal values(1966,'Frederiksberg C');
insert into Postal values(1967,'Frederiksberg C');
insert into Postal values(1970,'Frederiksberg C');
insert into Postal values(1971,'Frederiksberg C');
insert into Postal values(1972,'Frederiksberg C');
insert into Postal values(1973,'Frederiksberg C');
insert into Postal values(1974,'Frederiksberg C');
insert into Postal values(2000,'Frederiksberg');
insert into Postal values(2100,'København Ø');
insert into Postal values(2150,'Nordhavn');
insert into Postal values(2200,'København N');
insert into Postal values(2300,'København S');
insert into Postal values(2400,'København NV');
insert into Postal values(2450,'København SV');
insert into Postal values(2500,'Valby');
insert into Postal values(2600,'Glostrup');
insert into Postal values(2605,'Brøndby');
insert into Postal values(2610,'Rødovre');
insert into Postal values(2620,'Albertslund');
insert into Postal values(2625,'Vallensbæk');
insert into Postal values(2630,'Taastrup');
insert into Postal values(2635,'Ishøj');
insert into Postal values(2640,'Hedehusene');
insert into Postal values(2650,'Hvidovre');
insert into Postal values(2660,'Brøndby Strand');
insert into Postal values(2665,'Vallensbæk Strand');
insert into Postal values(2670,'Greve');
insert into Postal values(2680,'Solrød Strand');
insert into Postal values(2690,'Karlslunde');
insert into Postal values(2700,'Brønshøj');
insert into Postal values(2720,'Vanløse');
insert into Postal values(2730,'Herlev');
insert into Postal values(2740,'Skovlunde');
insert into Postal values(2750,'Ballerup');
insert into Postal values(2760,'Måløv');
insert into Postal values(2765,'Smørum');
insert into Postal values(2770,'Kastrup');
insert into Postal values(2791,'Dragør');
insert into Postal values(2800,'Kongens Lyngby');
insert into Postal values(2820,'Gentofte');
insert into Postal values(2830,'Virum');
insert into Postal values(2840,'Holte');
insert into Postal values(2850,'Nærum');
insert into Postal values(2860,'Søborg');
insert into Postal values(2870,'Dyssegård');
insert into Postal values(2880,'Bagsværd');
insert into Postal values(2900,'Hellerup');
insert into Postal values(2920,'Charlottenlund');
insert into Postal values(2930,'Klampenborg');
insert into Postal values(2942,'Skodsborg');
insert into Postal values(2950,'Vedbæk');
insert into Postal values(2960,'Rungsted Kyst');
insert into Postal values(2970,'Hørsholm');
insert into Postal values(2980,'Kokkedal');
insert into Postal values(2990,'Nivå');
insert into Postal values(3000,'Helsingør');
insert into Postal values(3050,'Humlebæk');
insert into Postal values(3060,'Espergærde');
insert into Postal values(3070,'Snekkersten');
insert into Postal values(3080,'Tikøb');
insert into Postal values(3100,'Hornbæk');
insert into Postal values(3120,'Dronningmølle');
insert into Postal values(3140,'Ålsgårde');
insert into Postal values(3150,'Hellebæk');
insert into Postal values(3200,'Helsinge');
insert into Postal values(3210,'Vejby');
insert into Postal values(3220,'Tisvildeleje');
insert into Postal values(3230,'Græsted');
insert into Postal values(3250,'Gilleleje');
insert into Postal values(3300,'Frederiksværk');
insert into Postal values(3310,'Ølsted');
insert into Postal values(3320,'Skævinge');
insert into Postal values(3330,'Gørløse');
insert into Postal values(3360,'Liseleje');
insert into Postal values(3370,'Melby');
insert into Postal values(3390,'Hundested');
insert into Postal values(3400,'Hillerød');
insert into Postal values(3450,'Allerød');
insert into Postal values(3460,'Birkerød');
insert into Postal values(3480,'Fredensborg');
insert into Postal values(3490,'Kvistgård');
insert into Postal values(3500,'Værløse');
insert into Postal values(3520,'Farum');
insert into Postal values(3540,'Lynge');
insert into Postal values(3550,'Slangerup');
insert into Postal values(3600,'Frederikssund');
insert into Postal values(3630,'Jægerspris');
insert into Postal values(3650,'Ølstykke');
insert into Postal values(3660,'Stenløse');
insert into Postal values(3670,'Veksø Sjælland');
insert into Postal values(3700,'Rønne');
insert into Postal values(3720,'Aakirkeby');
insert into Postal values(3730,'Nexø');
insert into Postal values(3740,'Svaneke');
insert into Postal values(3751,'Østermarie');
insert into Postal values(3760,'Gudhjem');
insert into Postal values(3770,'Allinge');
insert into Postal values(3782,'Klemensker');
insert into Postal values(3790,'Hasle');
insert into Postal values(4000,'Roskilde');
insert into Postal values(4030,'Tune');
insert into Postal values(4040,'Jyllinge');
insert into Postal values(4050,'Skibby');
insert into Postal values(4060,'Kirke Såby');
insert into Postal values(4070,'Kirke Hyllinge');
insert into Postal values(4100,'Ringsted');
insert into Postal values(4129,'Ringsted');
insert into Postal values(4130,'Viby Sjælland');
insert into Postal values(4140,'Borup');
insert into Postal values(4160,'Herlufmagle');
insert into Postal values(4171,'Glumsø');
insert into Postal values(4173,'Fjenneslev');
insert into Postal values(4174,'Jystrup Midtsj');
insert into Postal values(4180,'Sorø');
insert into Postal values(4190,'Munke Bjergby');
insert into Postal values(4200,'Slagelse');
insert into Postal values(4220,'Korsør');
insert into Postal values(4230,'Skælskør');
insert into Postal values(4241,'Vemmelev');
insert into Postal values(4242,'Boeslunde');
insert into Postal values(4243,'Rude');
insert into Postal values(4250,'Fuglebjerg');
insert into Postal values(4261,'Dalmose');
insert into Postal values(4262,'Sandved');
insert into Postal values(4270,'Høng');
insert into Postal values(4281,'Gørlev');
insert into Postal values(4291,'Ruds Vedby');
insert into Postal values(4293,'Dianalund');
insert into Postal values(4295,'Stenlille');
insert into Postal values(4296,'Nyrup');
insert into Postal values(4300,'Holbæk');
insert into Postal values(4320,'Lejre');
insert into Postal values(4330,'Hvalsø');
insert into Postal values(4340,'Tølløse');
insert into Postal values(4350,'Ugerløse');
insert into Postal values(4360,'Kirke Eskilstrup');
insert into Postal values(4370,'Store Merløse');
insert into Postal values(4390,'Vipperød');
insert into Postal values(4400,'Kalundborg');
insert into Postal values(4420,'Regstrup');
insert into Postal values(4440,'Mørkøv');
insert into Postal values(4450,'Jyderup');
insert into Postal values(4460,'Snertinge');
insert into Postal values(4470,'Svebølle');
insert into Postal values(4480,'Store Fuglede');
insert into Postal values(4490,'Jerslev Sjælland');
insert into Postal values(4500,'Nykøbing Sj');
insert into Postal values(4520,'Svinninge');
insert into Postal values(4532,'Gislinge');
insert into Postal values(4534,'Hørve');
insert into Postal values(4540,'Fårevejle');
insert into Postal values(4550,'Asnæs');
insert into Postal values(4560,'Vig');
insert into Postal values(4571,'Grevinge');
insert into Postal values(4572,'Nørre Asmindrup');
insert into Postal values(4573,'Højby');
insert into Postal values(4581,'Rørvig');
insert into Postal values(4583,'Sjællands Odde');
insert into Postal values(4591,'Føllenslev');
insert into Postal values(4592,'Sejerø');
insert into Postal values(4593,'Eskebjerg');
insert into Postal values(4600,'Køge');
insert into Postal values(4621,'Gadstrup');
insert into Postal values(4622,'Havdrup');
insert into Postal values(4623,'Lille Skensved');
insert into Postal values(4632,'Bjæverskov');
insert into Postal values(4640,'Faxe');
insert into Postal values(4652,'Hårlev');
insert into Postal values(4653,'Karise');
insert into Postal values(4654,'Faxe Ladeplads');
insert into Postal values(4660,'Store Heddinge');
insert into Postal values(4671,'Strøby');
insert into Postal values(4672,'Klippinge');
insert into Postal values(4673,'Rødvig Stevns');
insert into Postal values(4681,'Herfølge');
insert into Postal values(4682,'Tureby');
insert into Postal values(4683,'Rønnede');
insert into Postal values(4684,'Holmegaard');
insert into Postal values(4690,'Haslev');
insert into Postal values(4700,'Næstved');
insert into Postal values(4720,'Præstø');
insert into Postal values(4733,'Tappernøje');
insert into Postal values(4735,'Mern');
insert into Postal values(4736,'Karrebæksminde');
insert into Postal values(4750,'Lundby');
insert into Postal values(4760,'Vordingborg');
insert into Postal values(4771,'Kalvehave');
insert into Postal values(4772,'Langebæk');
insert into Postal values(4773,'Stensved');
insert into Postal values(4780,'Stege');
insert into Postal values(4791,'Borre');
insert into Postal values(4792,'Askeby');
insert into Postal values(4793,'Bogø By');
insert into Postal values(4800,'Nykøbing F');
insert into Postal values(4840,'Nørre Alslev');
insert into Postal values(4850,'Stubbekøbing');
insert into Postal values(4862,'Guldborg');
insert into Postal values(4863,'Eskilstrup');
insert into Postal values(4871,'Horbelev');
insert into Postal values(4872,'Idestrup');
insert into Postal values(4873,'Væggerløse');
insert into Postal values(4874,'Gedser');
insert into Postal values(4880,'Nysted');
insert into Postal values(4891,'Toreby L');
insert into Postal values(4892,'Kettinge');
insert into Postal values(4894,'Øster Ulslev');
insert into Postal values(4895,'Errindlev');
insert into Postal values(4900,'Nakskov');
insert into Postal values(4912,'Harpelunde');
insert into Postal values(4913,'Horslunde');
insert into Postal values(4920,'Søllested');
insert into Postal values(4930,'Maribo');
insert into Postal values(4941,'Bandholm');
insert into Postal values(4943,'Torrig L');
insert into Postal values(4944,'Fejø');
insert into Postal values(4951,'Nørreballe');
insert into Postal values(4952,'Stokkemarke');
insert into Postal values(4953,'Vesterborg');
insert into Postal values(4960,'Holeby');
insert into Postal values(4970,'Rødby');
insert into Postal values(4983,'Dannemare');
insert into Postal values(4990,'Sakskøbing');
insert into Postal values(4992,'Midtsjælland USF P');
insert into Postal values(5000,'Odense C');
insert into Postal values(5029,'Odense C');
insert into Postal values(5100,'Odense C');
insert into Postal values(5200,'Odense V');
insert into Postal values(5210,'Odense NV');
insert into Postal values(5220,'Odense SØ');
insert into Postal values(5230,'Odense M');
insert into Postal values(5240,'Odense NØ');
insert into Postal values(5250,'Odense SV');
insert into Postal values(5260,'Odense S');
insert into Postal values(5270,'Odense N');
insert into Postal values(5290,'Marslev');
insert into Postal values(5300,'Kerteminde');
insert into Postal values(5320,'Agedrup');
insert into Postal values(5330,'Munkebo');
insert into Postal values(5350,'Rynkeby');
insert into Postal values(5370,'Mesinge');
insert into Postal values(5380,'Dalby');
insert into Postal values(5390,'Martofte');
insert into Postal values(5400,'Bogense');
insert into Postal values(5450,'Otterup');
insert into Postal values(5462,'Morud');
insert into Postal values(5463,'Harndrup');
insert into Postal values(5464,'Brenderup Fyn');
insert into Postal values(5466,'Asperup');
insert into Postal values(5471,'Søndersø');
insert into Postal values(5474,'Veflinge');
insert into Postal values(5485,'Skamby');
insert into Postal values(5491,'Blommenslyst');
insert into Postal values(5492,'Vissenbjerg');
insert into Postal values(5500,'Middelfart');
insert into Postal values(5540,'Ullerslev');
insert into Postal values(5550,'Langeskov');
insert into Postal values(5560,'Aarup');
insert into Postal values(5580,'Nørre Aaby');
insert into Postal values(5591,'Gelsted');
insert into Postal values(5592,'Ejby');
insert into Postal values(5600,'Faaborg');
insert into Postal values(5610,'Assens');
insert into Postal values(5620,'Glamsbjerg');
insert into Postal values(5631,'Ebberup');
insert into Postal values(5642,'Millinge');
insert into Postal values(5672,'Broby');
insert into Postal values(5683,'Haarby');
insert into Postal values(5690,'Tommerup');
insert into Postal values(5700,'Svendborg');
insert into Postal values(5750,'Ringe');
insert into Postal values(5762,'Vester Skerninge');
insert into Postal values(5771,'Stenstrup');
insert into Postal values(5772,'Kværndrup');
insert into Postal values(5792,'Årslev');
insert into Postal values(5800,'Nyborg');
insert into Postal values(5853,'Ørbæk');
insert into Postal values(5854,'Gislev');
insert into Postal values(5856,'Ryslinge');
insert into Postal values(5863,'Ferritslev Fyn');
insert into Postal values(5871,'Frørup');
insert into Postal values(5874,'Hesselager');
insert into Postal values(5881,'Skårup Fyn');
insert into Postal values(5882,'Vejstrup');
insert into Postal values(5883,'Oure');
insert into Postal values(5884,'Gudme');
insert into Postal values(5892,'Gudbjerg Sydfyn');
insert into Postal values(5900,'Rudkøbing');
insert into Postal values(5932,'Humble');
insert into Postal values(5935,'Bagenkop');
insert into Postal values(5953,'Tranekær');
insert into Postal values(5960,'Marstal');
insert into Postal values(5970,'Ærøskøbing');
insert into Postal values(5985,'Søby Ærø');
insert into Postal values(6000,'Kolding');
insert into Postal values(6040,'Egtved');
insert into Postal values(6051,'Almind');
insert into Postal values(6052,'Viuf');
insert into Postal values(6064,'Jordrup');
insert into Postal values(6070,'Christiansfeld');
insert into Postal values(6091,'Bjert');
insert into Postal values(6092,'Sønder Stenderup');
insert into Postal values(6093,'Sjølund');
insert into Postal values(6094,'Hejls');
insert into Postal values(6100,'Haderslev');
insert into Postal values(6200,'Aabenraa');
insert into Postal values(6230,'Rødekro');
insert into Postal values(6240,'Løgumkloster');
insert into Postal values(6261,'Bredebro');
insert into Postal values(6270,'Tønder');
insert into Postal values(6280,'Højer');
insert into Postal values(6300,'Gråsten');
insert into Postal values(6310,'Broager');
insert into Postal values(6320,'Egernsund');
insert into Postal values(6330,'Padborg');
insert into Postal values(6340,'Kruså');
insert into Postal values(6360,'Tinglev');
insert into Postal values(6372,'Bylderup-Bov');
insert into Postal values(6392,'Bolderslev');
insert into Postal values(6400,'Sønderborg');
insert into Postal values(6430,'Nordborg');
insert into Postal values(6440,'Augustenborg');
insert into Postal values(6470,'Sydals');
insert into Postal values(6500,'Vojens');
insert into Postal values(6510,'Gram');
insert into Postal values(6520,'Toftlund');
insert into Postal values(6534,'Agerskov');
insert into Postal values(6535,'Branderup J');
insert into Postal values(6541,'Bevtoft');
insert into Postal values(6560,'Sommersted');
insert into Postal values(6580,'Vamdrup');
insert into Postal values(6600,'Vejen');
insert into Postal values(6621,'Gesten');
insert into Postal values(6622,'Bække');
insert into Postal values(6623,'Vorbasse');
insert into Postal values(6630,'Rødding');
insert into Postal values(6640,'Lunderskov');
insert into Postal values(6650,'Brørup');
insert into Postal values(6660,'Lintrup');
insert into Postal values(6670,'Holsted');
insert into Postal values(6682,'Hovborg');
insert into Postal values(6683,'Føvling');
insert into Postal values(6690,'Gørding');
insert into Postal values(6700,'Esbjerg');
insert into Postal values(6701,'Esbjerg');
insert into Postal values(6705,'Esbjerg Ø');
insert into Postal values(6710,'Esbjerg V');
insert into Postal values(6715,'Esbjerg N');
insert into Postal values(6720,'Fanø');
insert into Postal values(6731,'Tjæreborg');
insert into Postal values(6740,'Bramming');
insert into Postal values(6752,'Glejbjerg');
insert into Postal values(6753,'Agerbæk');
insert into Postal values(6760,'Ribe');
insert into Postal values(6771,'Gredstedbro');
insert into Postal values(6780,'Skærbæk');
insert into Postal values(6792,'Rømø');
insert into Postal values(6800,'Varde');
insert into Postal values(6818,'Årre');
insert into Postal values(6823,'Ansager');
insert into Postal values(6830,'Nørre Nebel');
insert into Postal values(6840,'Oksbøl');
insert into Postal values(6851,'Janderup Vestj');
insert into Postal values(6852,'Billum');
insert into Postal values(6853,'Vejers Strand');
insert into Postal values(6854,'Henne');
insert into Postal values(6855,'Outrup');
insert into Postal values(6857,'Blåvand');
insert into Postal values(6862,'Tistrup');
insert into Postal values(6870,'Ølgod');
insert into Postal values(6880,'Tarm');
insert into Postal values(6893,'Hemmet');
insert into Postal values(6900,'Skjern');
insert into Postal values(6920,'Videbæk');
insert into Postal values(6933,'Kibæk');
insert into Postal values(6940,'Lem St');
insert into Postal values(6950,'Ringkøbing');
insert into Postal values(6960,'Hvide Sande');
insert into Postal values(6971,'Spjald');
insert into Postal values(6973,'Ørnhøj');
insert into Postal values(6980,'Tim');
insert into Postal values(6990,'Ulfborg');
insert into Postal values(7000,'Fredericia');
insert into Postal values(7007,'Fredericia');
insert into Postal values(7017,'Taulov Pakkecenter');
insert into Postal values(7018,'Pakker TLP');
insert into Postal values(7029,'Fredericia');
insert into Postal values(7080,'Børkop');
insert into Postal values(7100,'Vejle');
insert into Postal values(7120,'Vejle Øst');
insert into Postal values(7130,'Juelsminde');
insert into Postal values(7140,'Stouby');
insert into Postal values(7150,'Barrit');
insert into Postal values(7160,'Tørring');
insert into Postal values(7171,'Uldum');
insert into Postal values(7173,'Vonge');
insert into Postal values(7182,'Bredsten');
insert into Postal values(7183,'Randbøl');
insert into Postal values(7184,'Vandel');
insert into Postal values(7190,'Billund');
insert into Postal values(7200,'Grindsted');
insert into Postal values(7250,'Hejnsvig');
insert into Postal values(7260,'Sønder Omme');
insert into Postal values(7270,'Stakroge');
insert into Postal values(7280,'Sønder Felding');
insert into Postal values(7300,'Jelling');
insert into Postal values(7321,'Gadbjerg');
insert into Postal values(7323,'Give');
insert into Postal values(7330,'Brande');
insert into Postal values(7361,'Ejstrupholm');
insert into Postal values(7362,'Hampen');
insert into Postal values(7400,'Herning');
insert into Postal values(7429,'Herning');
insert into Postal values(7430,'Ikast');
insert into Postal values(7441,'Bording');
insert into Postal values(7442,'Engesvang');
insert into Postal values(7451,'Sunds');
insert into Postal values(7470,'Karup J');
insert into Postal values(7480,'Vildbjerg');
insert into Postal values(7490,'Aulum');
insert into Postal values(7500,'Holstebro');
insert into Postal values(7540,'Haderup');
insert into Postal values(7550,'Sørvad');
insert into Postal values(7560,'Hjerm');
insert into Postal values(7570,'Vemb');
insert into Postal values(7600,'Struer');
insert into Postal values(7620,'Lemvig');
insert into Postal values(7650,'Bøvlingbjerg');
insert into Postal values(7660,'Bækmarksbro');
insert into Postal values(7673,'Harboøre');
insert into Postal values(7680,'Thyborøn');
insert into Postal values(7700,'Thisted');
insert into Postal values(7730,'Hanstholm');
insert into Postal values(7741,'Frøstrup');
insert into Postal values(7742,'Vesløs');
insert into Postal values(7752,'Snedsted');
insert into Postal values(7755,'Bedsted Thy');
insert into Postal values(7760,'Hurup Thy');
insert into Postal values(7770,'Vestervig');
insert into Postal values(7790,'Thyholm');
insert into Postal values(7800,'Skive');
insert into Postal values(7830,'Vinderup');
insert into Postal values(7840,'Højslev');
insert into Postal values(7850,'Stoholm Jyll');
insert into Postal values(7860,'Spøttrup');
insert into Postal values(7870,'Roslev');
insert into Postal values(7884,'Fur');
insert into Postal values(7900,'Nykøbing M');
insert into Postal values(7950,'Erslev');
insert into Postal values(7960,'Karby');
insert into Postal values(7970,'Redsted M');
insert into Postal values(7980,'Vils');
insert into Postal values(7990,'Øster Assels');
insert into Postal values(7992,'Sydjylland/Fyn USF P');
insert into Postal values(7993,'Sydjylland/Fyn USF B');
insert into Postal values(7996,'Fakturaservice');
insert into Postal values(7997,'Fakturascanning');
insert into Postal values(7998,'Statsservice');
insert into Postal values(7999,'Kommunepost');
insert into Postal values(8000,'Aarhus C');
insert into Postal values(8100,'Aarhus C');
insert into Postal values(8200,'Aarhus N');
insert into Postal values(8210,'Aarhus V');
insert into Postal values(8220,'Brabrand');
insert into Postal values(8229,'Risskov Ø');
insert into Postal values(8230,'Åbyhøj');
insert into Postal values(8240,'Risskov');
insert into Postal values(8245,'Risskov Ø');
insert into Postal values(8250,'Egå');
insert into Postal values(8260,'Viby J');
insert into Postal values(8270,'Højbjerg');
insert into Postal values(8300,'Odder');
insert into Postal values(8305,'Samsø');
insert into Postal values(8310,'Tranbjerg J');
insert into Postal values(8320,'Mårslet');
insert into Postal values(8330,'Beder');
insert into Postal values(8340,'Malling');
insert into Postal values(8350,'Hundslund');
insert into Postal values(8355,'Solbjerg');
insert into Postal values(8361,'Hasselager');
insert into Postal values(8362,'Hørning');
insert into Postal values(8370,'Hadsten');
insert into Postal values(8380,'Trige');
insert into Postal values(8381,'Tilst');
insert into Postal values(8382,'Hinnerup');
insert into Postal values(8400,'Ebeltoft');
insert into Postal values(8410,'Rønde');
insert into Postal values(8420,'Knebel');
insert into Postal values(8444,'Balle');
insert into Postal values(8450,'Hammel');
insert into Postal values(8462,'Harlev J');
insert into Postal values(8464,'Galten');
insert into Postal values(8471,'Sabro');
insert into Postal values(8472,'Sporup');
insert into Postal values(8500,'Grenaa');
insert into Postal values(8520,'Lystrup');
insert into Postal values(8530,'Hjortshøj');
insert into Postal values(8541,'Skødstrup');
insert into Postal values(8543,'Hornslet');
insert into Postal values(8544,'Mørke');
insert into Postal values(8550,'Ryomgård');
insert into Postal values(8560,'Kolind');
insert into Postal values(8570,'Trustrup');
insert into Postal values(8581,'Nimtofte');
insert into Postal values(8585,'Glesborg');
insert into Postal values(8586,'Ørum Djurs');
insert into Postal values(8592,'Anholt');
insert into Postal values(8600,'Silkeborg');
insert into Postal values(8620,'Kjellerup');
insert into Postal values(8632,'Lemming');
insert into Postal values(8641,'Sorring');
insert into Postal values(8643,'Ans By');
insert into Postal values(8653,'Them');
insert into Postal values(8654,'Bryrup');
insert into Postal values(8660,'Skanderborg');
insert into Postal values(8670,'Låsby');
insert into Postal values(8680,'Ry');
insert into Postal values(8700,'Horsens');
insert into Postal values(8721,'Daugård');
insert into Postal values(8722,'Hedensted');
insert into Postal values(8723,'Løsning');
insert into Postal values(8732,'Hovedgård');
insert into Postal values(8740,'Brædstrup');
insert into Postal values(8751,'Gedved');
insert into Postal values(8752,'Østbirk');
insert into Postal values(8762,'Flemming');
insert into Postal values(8763,'Rask Mølle');
insert into Postal values(8765,'Klovborg');
insert into Postal values(8766,'Nørre Snede');
insert into Postal values(8781,'Stenderup');
insert into Postal values(8783,'Hornsyld');
insert into Postal values(8800,'Viborg');
insert into Postal values(8830,'Tjele');
insert into Postal values(8831,'Løgstrup');
insert into Postal values(8832,'Skals');
insert into Postal values(8840,'Rødkærsbro');
insert into Postal values(8850,'Bjerringbro');
insert into Postal values(8860,'Ulstrup');
insert into Postal values(8870,'Langå');
insert into Postal values(8881,'Thorsø');
insert into Postal values(8882,'Fårvang');
insert into Postal values(8883,'Gjern');
insert into Postal values(8900,'Randers C');
insert into Postal values(8920,'Randers NV');
insert into Postal values(8930,'Randers NØ');
insert into Postal values(8940,'Randers SV');
insert into Postal values(8950,'Ørsted');
insert into Postal values(8960,'Randers SØ');
insert into Postal values(8961,'Allingåbro');
insert into Postal values(8963,'Auning');
insert into Postal values(8970,'Havndal');
insert into Postal values(8981,'Spentrup');
insert into Postal values(8983,'Gjerlev J');
insert into Postal values(8990,'Fårup');
insert into Postal values(9000,'Aalborg');
insert into Postal values(9029,'Aalborg');
insert into Postal values(9100,'Aalborg');
insert into Postal values(9200,'Aalborg SV');
insert into Postal values(9210,'Aalborg SØ');
insert into Postal values(9220,'Aalborg Øst');
insert into Postal values(9230,'Svenstrup J');
insert into Postal values(9240,'Nibe');
insert into Postal values(9260,'Gistrup');
insert into Postal values(9270,'Klarup');
insert into Postal values(9280,'Storvorde');
insert into Postal values(9293,'Kongerslev');
insert into Postal values(9300,'Sæby');
insert into Postal values(9310,'Vodskov');
insert into Postal values(9320,'Hjallerup');
insert into Postal values(9330,'Dronninglund');
insert into Postal values(9340,'Asaa');
insert into Postal values(9352,'Dybvad');
insert into Postal values(9362,'Gandrup');
insert into Postal values(9370,'Hals');
insert into Postal values(9380,'Vestbjerg');
insert into Postal values(9381,'Sulsted');
insert into Postal values(9382,'Tylstrup');
insert into Postal values(9400,'Nørresundby');
insert into Postal values(9430,'Vadum');
insert into Postal values(9440,'Aabybro');
insert into Postal values(9460,'Brovst');
insert into Postal values(9480,'Løkken');
insert into Postal values(9490,'Pandrup');
insert into Postal values(9492,'Blokhus');
insert into Postal values(9493,'Saltum');
insert into Postal values(9500,'Hobro');
insert into Postal values(9510,'Arden');
insert into Postal values(9520,'Skørping');
insert into Postal values(9530,'Støvring');
insert into Postal values(9541,'Suldrup');
insert into Postal values(9550,'Mariager');
insert into Postal values(9560,'Hadsund');
insert into Postal values(9574,'Bælum');
insert into Postal values(9575,'Terndrup');
insert into Postal values(9600,'Aars');
insert into Postal values(9610,'Nørager');
insert into Postal values(9620,'Aalestrup');
insert into Postal values(9631,'Gedsted');
insert into Postal values(9632,'Møldrup');
insert into Postal values(9640,'Farsø');
insert into Postal values(9670,'Løgstør');
insert into Postal values(9681,'Ranum');
insert into Postal values(9690,'Fjerritslev');
insert into Postal values(9700,'Brønderslev');
insert into Postal values(9740,'Jerslev J');
insert into Postal values(9750,'Østervrå');
insert into Postal values(9760,'Vrå');
insert into Postal values(9800,'Hjørring');
insert into Postal values(9830,'Tårs');
insert into Postal values(9850,'Hirtshals');
insert into Postal values(9870,'Sindal');
insert into Postal values(9881,'Bindslev');
insert into Postal values(9900,'Frederikshavn');
insert into Postal values(9940,'Læsø');
insert into Postal values(9970,'Strandby');
insert into Postal values(9981,'Jerup');
insert into Postal values(9982,'Ålbæk');
insert into Postal values(9990,'Skagen');
insert into Postal values(9992,'Jylland USF P');
insert into Postal values(9993,'Jylland USF B');
insert into Postal values(9996,'Fakturaservice');
insert into Postal values(9997,'Fakturascanning');
insert into Postal values(9998,'Borgerservice');
insert into Postal values(2412,'Santa Claus/Julemanden');
insert into Postal values(3900,'Nuuk');
insert into Postal values(3905,'Nuussuaq');
insert into Postal values(3910,'Kangerlussuaq');
insert into Postal values(3911,'Sisimiut');
insert into Postal values(3912,'Maniitsoq');
insert into Postal values(3913,'Tasiilaq');
insert into Postal values(3915,'Kulusuk');
insert into Postal values(3919,'Alluitsup Paa');
insert into Postal values(3920,'Qaqortoq');
insert into Postal values(3921,'Narsaq');
insert into Postal values(3922,'Nanortalik');
insert into Postal values(3923,'Narsarsuaq');
insert into Postal values(3924,'Ikerasassuaq');
insert into Postal values(3930,'Kangilinnguit');
insert into Postal values(3932,'Arsuk');
insert into Postal values(3940,'Paamiut');
insert into Postal values(3950,'Aasiaat');
insert into Postal values(3951,'Qasigiannguit');
insert into Postal values(3952,'Ilulissat');
insert into Postal values(3953,'Qeqertarsuaq');
insert into Postal values(3955,'Kangaatsiaq');
insert into Postal values(3961,'Uummannaq');
insert into Postal values(3962,'Upernavik');
insert into Postal values(3964,'Qaarsut');
insert into Postal values(3970,'Pituffik');
insert into Postal values(3971,'Qaanaaq');
insert into Postal values(3972,'Station Nord');
insert into Postal values(3980,'Ittoqqortoormiit');
insert into Postal values(3982,'Mestersvig');
insert into Postal values(3984,'Danmarkshavn');
insert into Postal values(3985,'Constable Pynt');
insert into Postal values(3992,'Slædepatrulje Sirius');
insert into Postal values(100,'Tórshavn');
insert into Postal values(110,'Tórshavn ');
insert into Postal values(160,'Argir');
insert into Postal values(165,'Argir ');
insert into Postal values(175,'Kirkjubøur');
insert into Postal values(176,'Velbastadur');
insert into Postal values(177,'Sydradalur, Streymoy');
insert into Postal values(178,'Nordradalur');
insert into Postal values(180,'Kaldbak');
insert into Postal values(185,'Kaldbaksbotnur');
insert into Postal values(186,'Sund');
insert into Postal values(187,'Hvitanes');
insert into Postal values(188,'Hoyvík');
insert into Postal values(210,'Sandur');
insert into Postal values(215,'Sandur');
insert into Postal values(220,'Skálavík');
insert into Postal values(230,'Húsavík');
insert into Postal values(235,'Dalur');
insert into Postal values(236,'Skarvanes');
insert into Postal values(240,'Skopun');
insert into Postal values(260,'Skúvoy');
insert into Postal values(270,'Nólsoy');
insert into Postal values(280,'Hestur');
insert into Postal values(285,'Koltur');
insert into Postal values(286,'Stóra Dimun');
insert into Postal values(330,'Stykkid');
insert into Postal values(335,'Leynar');
insert into Postal values(336,'Skællingur');
insert into Postal values(340,'Kvívík');
insert into Postal values(350,'Vestmanna');
insert into Postal values(355,'Vestmanna');
insert into Postal values(358,'Válur');
insert into Postal values(360,'Sandavágur');
insert into Postal values(370,'Midvágur');
insert into Postal values(375,'Midvágur');
insert into Postal values(380,'Sørvágur');
insert into Postal values(385,'Vatnsoyrar');
insert into Postal values(386,'Bøur');
insert into Postal values(387,'Gásadalur');
insert into Postal values(388,'Mykines');
insert into Postal values(400,'Oyrarbakki');
insert into Postal values(405,'Oyrarbakki');
insert into Postal values(410,'Kollafjørdur');
insert into Postal values(415,'Oyrareingir');
insert into Postal values(416,'Signabøur');
insert into Postal values(420,'Hósvík');
insert into Postal values(430,'Hvalvík');
insert into Postal values(435,'Streymnes');
insert into Postal values(436,'Saksun');
insert into Postal values(437,'Nesvík');
insert into Postal values(438,'Langasandur');
insert into Postal values(440,'Haldarsvík');
insert into Postal values(445,'Tjørnuvík');
insert into Postal values(450,'Oyri');
insert into Postal values(460,'Nordskáli');
insert into Postal values(465,'Svináir');
insert into Postal values(466,'Ljósá');
insert into Postal values(470,'Eidi');
insert into Postal values(475,'Funningur');
insert into Postal values(476,'Gjógv');
insert into Postal values(477,'Funningsfjørdur');
insert into Postal values(478,'Elduvík');
insert into Postal values(480,'Skáli');
insert into Postal values(485,'Skálafjørdur');
insert into Postal values(490,'Strendur');
insert into Postal values(494,'Innan Glyvur');
insert into Postal values(495,'Kolbanargjógv');
insert into Postal values(496,'Morskranes');
insert into Postal values(497,'Selatrad');
insert into Postal values(510,'Gøta');
insert into Postal values(511,'Gøtugjógv');
insert into Postal values(512,'Nordragøta');
insert into Postal values(513,'Sydrugøta');
insert into Postal values(515,'Gøta');
insert into Postal values(520,'Leirvík');
insert into Postal values(530,'Fuglafjørdur');
insert into Postal values(535,'Fuglafjørdur');
insert into Postal values(600,'Saltangará');
insert into Postal values(610,'Saltangará');
insert into Postal values(620,'Runavík');
insert into Postal values(625,'Glyvrar');
insert into Postal values(626,'Lambareidi');
insert into Postal values(627,'Lambi');
insert into Postal values(640,'Rituvík');
insert into Postal values(645,'Æduvík');
insert into Postal values(650,'Toftir');
insert into Postal values(655,'Nes, Eysturoy');
insert into Postal values(656,'Saltnes');
insert into Postal values(660,'Søldarfjørdur');
insert into Postal values(665,'Skipanes');
insert into Postal values(666,'Gøtueidi');
insert into Postal values(690,'Oyndarfjørdur');
insert into Postal values(695,'Hellur');
insert into Postal values(700,'Klaksvík');
insert into Postal values(710,'Klaksvík');
insert into Postal values(725,'Nordoyri');
insert into Postal values(726,'Ánir');
insert into Postal values(727,'Árnafjørdur');
insert into Postal values(730,'Norddepil');
insert into Postal values(735,'Depil');
insert into Postal values(736,'Nordtoftir');
insert into Postal values(737,'Múli');
insert into Postal values(740,'Hvannasund');
insert into Postal values(750,'Vidareidi');
insert into Postal values(765,'Svinoy');
insert into Postal values(766,'Kirkja');
insert into Postal values(767,'Hattarvík');
insert into Postal values(780,'Kunoy');
insert into Postal values(785,'Haraldssund');
insert into Postal values(795,'Sydradalur, Kalsoy');
insert into Postal values(796,'Húsar');
insert into Postal values(797,'Mikladalur');
insert into Postal values(798,'Trøllanes');
insert into Postal values(800,'Tvøroyri');
insert into Postal values(810,'Tvøroyri');
insert into Postal values(825,'Frodba');
insert into Postal values(826,'Trongisvágur');
insert into Postal values(827,'Øravík');
insert into Postal values(850,'Hvalba');
insert into Postal values(860,'Sandvík');
insert into Postal values(870,'Fámjin');
insert into Postal values(900,'Vágur');
insert into Postal values(910,'Vágur');
insert into Postal values(925,'Nes, Vágur');
insert into Postal values(926,'Lopra');
insert into Postal values(927,'Akrar');
insert into Postal values(928,'Vikarbyrgi');
insert into Postal values(950,'Porkeri');
insert into Postal values(960,'Hov');
insert into Postal values(970,'Sumba');


insert into Person(cpr, title, firstName, lastName, postalCode, street, phone, email, password)
values
('121212-2990', 'Sir', 'Lance', 'Alot', 2990, 'Nivåhøj 74, 3, 1', '12345678', 'la@cphbank.dk', 'la'),
('010101-2000', 'Mr', 'Thomas', 'Svenningsen', 2000, 'Somewhere', '98765432', 'ts@cphbank.dk', 'ts'),
('020202-2635', 'Mr', 'Chris', 'Petersen', 2635, 'Ishøjvej 29', '13579113', 'cp@cphbank.dk', 'cp');
